### ISSUE TITLE
Join us in fighting covid as an iPXE expert

### ISSUE THREAD

**Issue by sokoow** [leigh-j/k3os-ipxe#1]
Hey,

Cool project, it ideally looks like you'd be able to help us with fighting COVID with it!

We're planning to use a lot of iPXE related things, and your expertise would be really useful for us.

Join us on: https://devpost.com/software/help-education-sector-to-produce-more-laptops-for-students

Greetings, Karol & the team.

**Comment by xeor** [comment]
lol

**Comment by xeor** [comment]
......
